apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: postgres-database
  labels:
    app: postgres
data:
  POSTGRES_USER: rental_system
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: rental_postgres

---
# DEPLOYMENT POSTGRES
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: postgres-database
spec:
  # serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
