version: '3'

networks:
  fastapi-networks:
    driver: bridge

services:

  fastapi:
    image: ${DOCKER_MAIN_IMAGE}
    container_name: rental_service
    depends_on:
      - db
    ports:
      - '8000:8080'
    env_file:
      - ./.env
    networks:
      - fastapi-networks
    volumes:
      - static:/static
      - ./:/usr/src/app:ro

  nginx: 
    build: ./nginx
    container_name: nginx
    volumes:
      - static:/static
    ports:
      - '80:80'
    depends_on:
      - fastapi
    networks:
      - fastapi-networks

  db:
    # depends_on:
    #   - db_test
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - fastapi-networks

  db_test:
    image: postgres
    container_name: postgres_test
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=rental_postgres_test
    ports:
      - '7878:5432'
    networks:
      - fastapi-networks

volumes:
  static:
  db:
    driver: local