kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  # namespace: rental-system
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  namespace: rental-system
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: rental-system
  labels:
    app: postgres
data:
  POSTGRES_DB: rental_postgres
  POSTGRES_USER: rental_system
  POSTGRES_PASSWORD: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  # namespace: rental-system
  labels:
    app: postgres
spec:
  ports:
    - name: postgres
      port: 5432
      nodePort: 30432
  type: NodePort
  selector:
    app: postgres
# kubectl delete pvc postgres-pv-claim && kubectl delete pv postgres-pv-volume && kubectl delete deployment postgres && kubectl delete service postgres
