pipeline {
    agent any

    stages {
        stage('Build') {

            environment {
                DOCKER_HUB_CREDENTIALS=credentials('dockerhub')
                DOCKER_IMAGE=credentials('dockerimage')
                USER_CREDENTIALS=credentials('user')
            }

            steps {
                sh """
                    echo $USER_CREDENTIALS_PSW | sudo -E -S apt-get update && sudo apt-get upgrade -y
                    echo $USER_CREDENTIALS_PSW | sudo -E -S apt-get install python3-pip -y
                    echo $USER_CREDENTIALS_PSW | sudo -E -S apt-get upgrade -y
                    pip3 install --no-cache-dir -r requirements.txt 
                    echo $USER_CREDENTIALS_PSW | sudo -E -S apt-get upgrade -y
                """
                sh """
                    echo $USER_CREDENTIALS_PSW | sudo -E -S su - $USER_CREDENTIALS_USR
                    echo $USER_CREDENTIALS_PSW | echo $DOCKER_HUB_CREDENTIALS_PSW | sudo -E -S docker login -u $DOCKER_HUB_CREDENTIALS_USR --password-stdin
                    echo $USER_CREDENTIALS_PSW | sudo docker build -t $DOCKER_IMAGE .
                    echo $USER_CREDENTIALS_PSW | sudo docker push $DOCKER_IMAGE .
                """



                    
            }
        }

        stage('Testing') {
            steps {
                echo 'Testing'
            }
        }
        
        stage('Deploy') {
            steps {
                echo 'Deploy'
            }
        }
    }
}
