pipeline {
    agent any

    stages {
        stage('Build') {

            environment {
                DOCKER_HUB_CREDENTIALS=credentials('dockerhub')
                DOCKER_IMAGE=credentials('dockerimage')
                USER_CREDENTIALS=credentials('user')
            }

            steps {
                // sh "sudo docker --version"
                // sh "echo $USER_CREDENTIALS_PSW | echo $USER_CREDENTIALS_PSW  | sudo -E -S su - $USER_CREDENTIALS_USR"
                sh "echo $USER_CREDENTIALS_PSW | echo $DOCKER_HUB_CREDENTIALS_PSW | sudo -E -S docker login -u $DOCKER_HUB_CREDENTIALS_USR --password-stdin"
                // sh """
                //     sudo apt-get update && sudo apt-get upgrade -y
                //     sudo apt-get install python3-pip -y
                //     sudo apt-get upgrade -y
                //     pip3 install --no-cache-dir -r requirements.txt 
                //     sudo apt-get upgrade -y
                // """
                    
            }
        }

        stage('Testing') {
            steps {
                echo 'Testing'
            }
        }
        
        stage('Deploy') {
            steps {
                echo 'Deploy'
            }
        }
    }
}
